defmodule CritWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :crit

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_crit_key",
    signing_salt: "vMlH9JxO",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :uri, :user_agent, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :uri, :user_agent, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :crit,
    gzip: not code_reloading?,
    only: CritWeb.static_paths(),
    only_matching: CritWeb.static_paths_matching(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :crit
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug CritWeb.Plugs.CanonicalHost
  plug Plug.Session, @session_options

  # Drop request body and cookies — review documents and comment bodies must
  # never leave the deployment. Placed after Session/MethodOverride so the
  # captured context reflects the final method and session state.
  plug Sentry.PlugContext,
    body_scrubber: nil,
    cookie_scrubber: nil

  plug CritWeb.Router
end
